server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.baemin.dto
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521
    username: [입력]
    password: [입력]

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [입력]
            client-secret: [입력]
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
            
          kakao:            
            client-id: [입력]
            client-secret: [입력]
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
            
          naver:
            client-id: [입력]
            client-secret: [입력]
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:  
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  
            
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail :
    host : smtp.gmail.com
    port : 587
    username : [google id]
    password : [google app password]
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

imp_key: [입력]
imp_secret: [입력]